if(NOT PREFIX)
    set(PREFIX "${_vk_opencv_prefix}")
endif()
if(NOT EXISTS "${PREFIX}/lib/libopencv_core.a")
    message(FATAL_ERROR "OpenCV core archive is missing from ${PREFIX}")
endif()
foreach(_vk_excluded IN ITEMS dnn highgui videoio imgcodecs gapi ml photo stitching python2 python3 java)
    if(EXISTS "${PREFIX}/lib/libopencv_${_vk_excluded}.a")
        message(FATAL_ERROR "Excluded OpenCV module found: ${_vk_excluded}")
    endif()
endforeach()
foreach(_vk_required IN ITEMS core imgproc calib3d features2d flann objdetect)
    if(NOT EXISTS "${PREFIX}/lib/libopencv_${_vk_required}.a")
        message(FATAL_ERROR "Required OpenCV module missing: ${_vk_required}")
    endif()
endforeach()
