// Regenerate with the pinned planner; RobotKit consumes these values without linking it.
#include "motionkit.h"
#include <cassert>
#include <cstdio>

int main() {
    std::puts("// Generated by motionkit/native/tools/generate-runtime-fixtures.cpp. Do not edit.\n#pragma once\n#include \"trajectory_core.h\"\n#include <cassert>\nnamespace runtime_fixtures {");
    for (unsigned kind = 0; kind < 4; ++kind) {
        const char *names[] = {"rest_two", "moving_two", "rest_short_two", "rest_one"};
        mk_state_to_state_request request{};
        request.struct_size = sizeof(request);
        request.joint_count = kind == 3 ? 1 : 2;
        request.synchronization = MK_SYNCHRONIZATION_TIME;
        for (unsigned j = 0; j < request.joint_count; ++j) {
            const double sign = j == 0 ? 1 : -1;
            request.target_position[j] = sign * (kind == 1 || kind == 2 ? 0.25 : 0.5);
            request.current_velocity[j] = kind == 1 ? sign * 0.5 : 0;
            request.max_velocity[j] = 1;
            request.max_acceleration[j] = kind == 1 || kind == 2 ? 1 : 2;
            request.max_jerk[j] = kind == 3 ? 5 : 4;
        }
        mk_trajectory_handle trajectory{};
        int result = 0;
        assert(mk_generate_state_to_state(&request, &trajectory, &result) == MK_OK);
        unsigned count = 0;
        assert(mk_trajectory_segment_count(trajectory, &count) == MK_OK);
        std::printf("inline mk_result %s(mk_trajectory_handle *out) {\n    auto status = mk_trajectory_create(%u, out);\n    if (status != MK_OK) return status;\n", names[kind], request.joint_count);
        for (unsigned index = 0; index < count; ++index) {
            mk_segment segment{};
            segment.struct_size = sizeof(segment);
            assert(mk_trajectory_get_segment(trajectory, index, &segment) == MK_OK);
            std::printf("    {\n        mk_segment segment{};\n        segment.struct_size = sizeof(segment);\n        segment.joint_count = %u;\n        segment.t0_ns = %lld;\n        segment.duration_ns = %lld;\n        segment.degree = %u;\n", segment.joint_count, (long long)segment.t0_ns, (long long)segment.duration_ns, segment.degree);
            for (unsigned j = 0; j < segment.joint_count; ++j)
                for (unsigned d = 0; d <= segment.degree; ++d)
                    std::printf("        segment.coefficients[%u].value[%u] = %.17g;\n", j, d, segment.coefficients[j].value[d]);
            std::puts("        status = mk_trajectory_append_segment(*out, &segment);\n        if (status != MK_OK) { mk_trajectory_destroy(*out); out->id = 0; return status; }\n    }");
        }
        std::puts("    return MK_OK;\n}");
        mk_trajectory_destroy(trajectory);
    }
    std::puts("} // namespace runtime_fixtures");
}
