package app;

/** Generated by tools/check-script-identity.py --write. */
class ScriptSourceManifest {
  public static inline var TWO_ROBOT_SHA256 = "b483069ae80dad3c1def45b24f3c13b1b4641d723cf71ca70de2496e7077730e";
}
