package app;

/** Generated by tools/check-script-identity.py --write. */
class ScriptSourceManifest {
  public static inline var TWO_ROBOT_SHA256 = "b67ecbce6a951e07c471881f729c5112c23eb9b9309ddaf7c96ad862be6cb00a";
}
